# Form implementation generated from reading ui file 'C:\Users\APC\Projects\robotics-programming-platform\editor\assets\uis\project_main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StartMainWindow(object):
    def setupUi(self, StartMainWindow):
        StartMainWindow.setObjectName("StartMainWindow")
        StartMainWindow.resize(425, 471)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StartMainWindow.sizePolicy().hasHeightForWidth())
        StartMainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=StartMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        StartMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=StartMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 425, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        StartMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=StartMainWindow)
        self.statusbar.setObjectName("statusbar")
        StartMainWindow.setStatusBar(self.statusbar)
        self.newProjectAction = QtGui.QAction(parent=StartMainWindow)
        self.newProjectAction.setObjectName("newProjectAction")
        self.openProjectAction = QtGui.QAction(parent=StartMainWindow)
        self.openProjectAction.setObjectName("openProjectAction")
        self.saveProjectAction = QtGui.QAction(parent=StartMainWindow)
        self.saveProjectAction.setObjectName("saveProjectAction")
        self.saveAsProjectAction = QtGui.QAction(parent=StartMainWindow)
        self.saveAsProjectAction.setObjectName("saveAsProjectAction")
        self.undoAction = QtGui.QAction(parent=StartMainWindow)
        self.undoAction.setObjectName("undoAction")
        self.actionSetting = QtGui.QAction(parent=StartMainWindow)
        self.actionSetting.setObjectName("actionSetting")
        self.menuFile.addAction(self.newProjectAction)
        self.menuFile.addAction(self.openProjectAction)
        self.menuFile.addAction(self.saveProjectAction)
        self.menuFile.addAction(self.saveAsProjectAction)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.undoAction)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSetting)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(StartMainWindow)
        QtCore.QMetaObject.connectSlotsByName(StartMainWindow)

    def retranslateUi(self, StartMainWindow):
        _translate = QtCore.QCoreApplication.translate
        StartMainWindow.setWindowTitle(_translate("StartMainWindow", "Project"))
        self.menuFile.setTitle(_translate("StartMainWindow", "File"))
        self.newProjectAction.setText(_translate("StartMainWindow", "New"))
        self.newProjectAction.setToolTip(_translate("StartMainWindow", "Create a new project"))
        self.newProjectAction.setShortcut(_translate("StartMainWindow", "Ctrl+Shift+N"))
        self.openProjectAction.setText(_translate("StartMainWindow", "Open"))
        self.openProjectAction.setShortcut(_translate("StartMainWindow", "Ctrl+Shift+O"))
        self.saveProjectAction.setText(_translate("StartMainWindow", "Save"))
        self.saveProjectAction.setShortcut(_translate("StartMainWindow", "Ctrl+S"))
        self.saveAsProjectAction.setText(_translate("StartMainWindow", "Save As"))
        self.saveAsProjectAction.setShortcut(_translate("StartMainWindow", "Ctrl+Shift+S"))
        self.undoAction.setText(_translate("StartMainWindow", "Undo"))
        self.undoAction.setShortcut(_translate("StartMainWindow", "Ctrl+Z"))
        self.actionSetting.setText(_translate("StartMainWindow", "Setting"))
